import { StyleSheet, Platform } from 'react-native';
import { moderateScale, verticalScale } from '../../utils/Responsive';
import { colors, Fonts } from '../../utils/theme';
import { defaultIconSizes } from '../../utils/CommonStyles';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  safeAreaHeader: {
    backgroundColor: colors.black,
  },
  header: {
    width: '100%',
    backgroundColor: colors.black,
    paddingTop: Platform.OS === 'android' ? verticalScale(14) : verticalScale(16),
    paddingBottom: Platform.OS === 'android' ? verticalScale(8) : verticalScale(16),
    marginTop: Platform.OS === 'android' ? verticalScale(16) : 0,
    marginBottom: Platform.OS === 'android' ? verticalScale(16) : 0,
    position: 'relative',
    overflow: 'visible',
  },
  scrollView: {
    flex: 1,
    backgroundColor: colors.white,
  },
  editIconWrapper: {
    position: 'absolute',
    top: moderateScale(40),
    right: moderateScale(-8),
    backgroundColor: colors.white,
    borderRadius: moderateScale(12),
    width: moderateScale(24),
    height: moderateScale(24),
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.divider,
    shadowColor: colors.black,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    zIndex: 2,
  },
  editIcon: {
    width: defaultIconSizes.xxsmall,
    height: defaultIconSizes.xxsmall,
  },

  profileContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: Platform.OS === 'android' ? verticalScale(4) : verticalScale(10),
    paddingHorizontal: moderateScale(16),
  },
  avatarContainer: {
    position: 'relative',
    width: Platform.OS === 'android' ? moderateScale(56) : moderateScale(60),
    height: Platform.OS === 'android' ? moderateScale(56) : moderateScale(60),
  },
  avatarWrapper: {
    width: '100%',
    height: '100%',
    borderRadius: 246,
    backgroundColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    opacity: 1,
  },
  profileTextContainer: {
    flex: 1,
    justifyContent: 'center',
    paddingLeft: moderateScale(16),
  },
  userRole: {
    fontFamily: Fonts.medium,
    fontWeight: '500',
    fontSize: Platform.OS === 'android' ? moderateScale(12) : moderateScale(14),
    lineHeight: Platform.OS === 'android' ? verticalScale(16) : verticalScale(20),
    letterSpacing: 0,
    color: colors.white,
    marginBottom: Platform.OS === 'android' ? verticalScale(4) : verticalScale(6),
    textTransform: 'uppercase',
  },
  menuIconContainer: {
    position: 'absolute',
    right: Platform.OS === 'android' ? 16 : 16,
    top: Platform.OS === 'android' ? verticalScale(8) : undefined,
    padding: moderateScale(8),
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 999,
    elevation: 10,
  },
  avatar: {
    width: '100%',
    height: '100%',
    borderRadius: moderateScale(999),
    resizeMode: 'cover',
    opacity: 1,
  },
  userName: {
    fontFamily: Fonts.bold,
    fontWeight: '700',
    fontSize: Platform.OS === 'android' ? moderateScale(20) : moderateScale(24),
    lineHeight: Platform.OS === 'android' ? verticalScale(24) : verticalScale(32),
    letterSpacing: -0.288, // -1.2% of 24px
    color: colors.white,
    marginBottom: Platform.OS === 'android' ? verticalScale(4) : verticalScale(6),
  },
  userMobile: {
    fontFamily: Fonts.regular,
    fontWeight: '400',
    fontSize: Platform.OS === 'android' ? moderateScale(12) : moderateScale(14),
    lineHeight: Platform.OS === 'android' ? verticalScale(16) : verticalScale(22.4), // 160% of 14px
    letterSpacing: 0,
    color: colors.white,
  },
  name: {
    fontSize: moderateScale(18),
    fontFamily: Fonts.medium,
    color: colors.black,
    marginBottom: verticalScale(4),
    textAlign: 'center',
  },
  email: {
    color: colors.white,
    marginBottom: verticalScale(6),
    textAlign: 'center',
  },
  menuContainer: {
    flex: 7,
    // marginTop: verticalScale(16),
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.3)',
  },

  logoutContainer: {
    padding: moderateScale(10),
    paddingHorizontal: moderateScale(13),
    borderTopWidth: 1,
    borderTopColor: colors.divider,
    backgroundColor: colors.white,
  },
  logoutButton: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  logoutText: {
    marginLeft: moderateScale(14),
    fontWeight: '500',
    fontSize: verticalScale(14),
    lineHeight: verticalScale(20),
    fontFamily: Fonts.medium,
    color: colors.Gray80,
  },
  versionFooter: {
    backgroundColor: colors.white,
    paddingVertical: verticalScale(12),
    paddingBottom: verticalScale(20),
    alignItems: 'center',
  },
  icon: {
    width: moderateScale(24),
    height: moderateScale(24),
  },
  drawerLabel: {
    marginLeft: moderateScale(6),
    fontWeight: '500',
    fontSize: verticalScale(14),
    lineHeight: verticalScale(20),
    fontFamily: Fonts.medium,
    color: colors.Gray80,
  },
  masterItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: moderateScale(14),
    paddingHorizontal: moderateScale(6),
    marginHorizontal: moderateScale(4),
  },
  masterItemContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: moderateScale(6),
    marginLeft: moderateScale(4),
  },
  masterLabel: {
    marginLeft: moderateScale(9),
    fontWeight: '500',
    fontSize: verticalScale(14),
    lineHeight: verticalScale(20),
    fontFamily: Fonts.medium,
    color: colors.Gray80,
  },
  subMenuContainer: {
    flexDirection: 'row',
    marginLeft: moderateScale(20),
    position: 'relative',
    paddingLeft: moderateScale(6),
  },
  lineContainer: {
    position: 'absolute',
    left: moderateScale(-1),
    width: 1,
    justifyContent: 'center',
  },
  verticalLine: {
    width: 1,
    height: '100%',
    backgroundColor: colors.Gray40,
  },
  subMenuItems: {
    flex: 1,
  },
  subMenuItem: {
    paddingLeft: moderateScale(4),
    marginVertical: moderateScale(-4),
  },
  versionText: {
    fontFamily: Fonts.regular,
    fontWeight: '400',
    fontSize: verticalScale(14),
    lineHeight: verticalScale(14) * 1.6,
    letterSpacing: 0,
    textAlign: 'center',
    color: colors.gray1000,
  },
});
