export const API_MESSAGES = {
  // Auth related messages
  auth: {
    invalidRequest: 'invalid request',
    userNotFound: 'user not found',
    waitOtpOneMin: 'wait otp one min',
    otpSentSuccessfully: 'otp sent successfully',
    multipleSmsToSameNumberNotAllowed: 'multiple sms to same number not allowed',
    somethingWentWrong: 'something went wrong',
    invalidOtp: 'invalid otp',
    otpVerifiedSuccessfully: 'otp verified successfully',
    waitBeforeResendOtp: 'Wait before resend OTP',
    otpResendSuccessfully: 'otp resend successfully',
    errBadRequest: 'bad request',
    loginSuccess: 'login success',
    unauthorizedAccess: 'unauthorized access',
    invalidOtpToken: 'invalid otp token',
    invalidRefreshToken: 'invalid refresh token',
  },
  category: {
    categoryAlreadyExists: 'category already exists',
    categoryNotFound: 'category not found',
    categoryCreatedSuccessfully: 'category created successfully',
    categoryUpdatedSuccessfully: 'category updated successfully',
    categoryDeletedSuccessfully: 'category deleted successfully',
    categoryStatusUpdatedSuccessfully: 'category status updated successfully',
    categoryListFetchedSuccessfully: 'category list fetched successfully',
    categoryFetchedSuccessfully: 'category fetched successfully',
  },
  road: {
    roadAlreadyExists: 'road already exists',
    roadNotFound: 'road not found',
    roadCreatedSuccessfully: 'road created successfully',
    roadUpdatedSuccessfully: 'road updated successfully',
    roadDeletedSuccessfully: 'road deleted successfully',
    roadStatusUpdatedSuccessfully: 'road status updated successfully',
    roadListFetchedSuccessfully: 'road list fetched successfully',
    roadFetchedSuccessfully: 'road fetched successfully',
  },
  concernType: {
    concernTypeAlreadyExists: 'concern type already exists',
    concernTypeNotFound: 'concern type not found',
    concernTypeCreatedSuccessfully: 'concern type created successfully',
    concernTypeUpdatedSuccessfully: 'concern type updated successfully',
    concernTypeDeletedSuccessfully: 'concern type deleted successfully',
    concernTypeListFetchedSuccessfully: 'concern type list fetched successfully',
    concernTypeFetchedSuccessfully: 'concern type fetched successfully',
  },
} as const;
