const Images = {
  LOGO: require('../assets/images/Logo.png'),
  OTP: require('../assets/images/OTP.png'),
  APP_BACKGROUND: require('../assets/images/Bgimage.jpg'),
  DELETE_IMAGE: require('../assets/icons/Delete.png'),
  EDIT_IMAGE: require('../assets/icons/Edit.png'),
  SAMPLE_IMAGE: require('../assets/icons/sample.png'),
  ARROW_BACK: require('../assets/icons/backIcon.png'),
  DELETE_POPUP_IMAGE: require('../assets/images/DeletePopup.png'),
  SELECT_ICON: require('../assets/icons/RightIcon.png'),
  RIGHT_ICON: require('../assets/icons/RightIcon.png'),
  UPLOAD_IMAGE_ICON: require('../assets/icons/imageUpload.png'),
  ADD_PRODUCT_ICON: require('../assets/icons/AddProductIcon.png'),
  FILTER_ICON: require('../assets/icons/FilterIcon.png'),
  SEARCH_ICON: require('../assets/icons/SearchIcon.png'),
  CLOSE_ICON: require('../assets/icons/CloseIcon.png'),
  WITH_SAMPLE: require('../assets/icons/WithSample.png'),
  SORTING_ICON: require('../assets/icons/SortIcon.png'),
  SELECT_ICON_FILTER: require('../assets/icons/SelectFilter.png'),
  DESELECT_ICON_FILTER: require('../assets/icons/DeselectFilter.png'),
  RIGET_SIDE_ICON: require('../assets/icons/RightSideIcon.png'),
  CLOSE_BUTTON_ICON: require('../assets/icons/closeButtonIcon.png'),
  SELECT_ITEM: require('../assets/icons/selectItemIcon.png'),
  DEFAULT_AVATAR: require('../assets/images/Avatar.png'),
  EMPTY_DATA_IMAGE: require('../assets/images/Nodata.png'),
  NO_INTERNET_IMAGE: require('../assets/images/noInternet.png'),
  OOPS_IMAGE: require('../assets/images/oops.png'),
  FORCE_UPDATE_IMAGE: require('../assets/images/forceUpdate.png'),
  SUCCESS_IMAGE: require('../assets/images/success.png'),
  ADD_IMAGE: require('../assets/images/Vector.png'),
  ADD_COMPANY_IMAGE: require('../assets/images/AddCopanyImage.png'),
  WAVES_IMAGE: require('../assets/images/Wave.png'),
  RENAME_COMPANY_IMAGE: require('../assets/images/renameCompany.png'),
  EDITSTAFF_INCHAT: require('../assets/images/EditUser.png'),
  APP_LOGO: require('../assets/images/Logo.png'),
};

export default Images;
